# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OpenCnR
# email: contact@opencnr.com
description: > # this means to ignore newlines until "baseurl:"
  OpenCnR is an open-source SA-MP Cops and Robbers game-mode!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://opencnr.com" # the base hostname & protocol for your site
twitter_username: opencnr
github_username: opencnr

# Build settings
markdown: kramdown
